CERTUTIL -addstore -f -v root "microsoft identity verification root certificate authority 2020.crt"
CERTUTIL -addstore -f -v root "DigiCert Assured ID Root CA.cer"
CERTUTIL -addstore -f -v root "DigiCert Global Root CA.cer"
CERTUTIL -addstore -f -v root "DigiCert Hight Assurance EV Root CA"
CERTUTIL -addstore -f -v root "DigiCertGlobalRootG2.crt"
CERTUTIL -addstore -f -v root "DigiCertTrustedRootG4.crt"
CERTUTIL -addstore -f -v root "pca3-g3.crt"
CERTUTIL -addstore -f -v root "SHA-2 Root  USERTrust RSA Certification Authority.crt"
CERTUTIL -addstore -f -v root "VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem"
CERTUTIL -addstore -f -v root "VeriSign-Universal-Root-Certification-Authority.pem"
CERTUTIL -addstore -f -v root "MicrosoftRootCertificateAuthority2011.cer"
CERTUTIL -addstore -f -v root "MicrosoftRootCertificateAuthority2010.cer"
CERTUTIL -addstore -f -v CA "DigiCertAssuredIDCodeSigningCA-1.crt"
CERTUTIL -addstore -f -v CA "DigiCertEVCodeSigningCA.crt"
CERTUTIL -addstore -f -v CA "DigiCertEVCodeSigningCA-SHA2.crt"
CERTUTIL -addstore -f -v CA "DigiCertHighAssuranceCodeSigningCA-1.crt"
CERTUTIL -addstore -f -v CA "DigiCertTrustedG4CodeSigningRSA4096SHA3842021CA1.crt"
CERTUTIL -addstore -f -v CA "Symantec_Class3_SHA256_code.crt"
